DECLARE
  V_CODICEFID CORSOPLSQL.CLIENTI.CODFIDELITY%TYPE := :CODFID;
  V_NOMINATIVO VARCHAR2(100);
BEGIN
  
  SELECT
    NOME || ' ' || COGNOME
  INTO
    V_NOMINATIVO
  FROM
    CORSOPLSQL.CLIENTI
  WHERE
    CODFIDELITY = V_CODICEFID;
  
  DBMS_OUTPUT.PUT_LINE('Il Nome del Cliente è ' || V_NOMINATIVO);

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NON è stato trovato alcun cliente!!!');
  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('Nominativo Troppo Lungo');
END;
