DECLARE
  V_CODFID VARCHAR2(20) := :CODFID;
  V_NUMSPESE BINARY_INTEGER := 0;
  V_CONTATORE BINARY_INTEGER := 0;
  V_NUMMINSPESE NUMBER := 15;
BEGIN
  
  SELECT
    COUNT(*)
  INTO
    V_NUMSPESE
  FROM
    CORSOPLSQL.SCONTRINI
  WHERE
    CODFID = V_CODFID;
  
  -- Espressione LOOP
  -- Si comporta simile all'istruzione do...while
  IF V_NUMSPESE > V_NUMMINSPESE THEN
    LOOP
      V_CONTATORE := V_CONTATORE + 1;
      DBMS_OUTPUT.PUT_LINE('Creato Bonus ' || V_CONTATORE);
      EXIT WHEN V_CONTATORE = V_NUMSPESE - V_NUMMINSPESE;
    END LOOP;
  END IF;

  DBMS_OUTPUT.PUT_LINE('Fatto!');
END;
