DECLARE
  V_CODFID VARCHAR2(20) := :CODFID;
  V_NUMSPESE BINARY_INTEGER := 0;
  V_CONTATORE BINARY_INTEGER := 0;
  V_BONUS NUMBER := 0;
BEGIN
  
  SELECT
    COUNT(*)
  INTO
    V_NUMSPESE
  FROM
    CORSOPLSQL.SCONTRINI
  WHERE
    CODFID = V_CODFID;
  
  V_CONTATORE := V_NUMSPESE - 15;

  -- Espressione WHILE
  WHILE V_CONTATORE > 0 LOOP
    DBMS_OUTPUT.PUT_LINE('Creato Bonus ' || V_CONTATORE);
    V_CONTATORE := V_CONTATORE - 1;
  
    IF V_BONUS > 0 THEN
      DBMS_OUTPUT.PUT_LINE('Bonus Massimo Raggiunto!');
      EXIT;
    END IF;
  
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('Fatto!');
END;
