-- Esempio di Record creati dall'utente
DECLARE
  -- 1°Record definito dall'utente
TYPE CARD_TYPE
IS
  RECORD
  (
    CODFIDELITY VARCHAR2(20),
    BOLLINI     NUMBER,
    ULTIMASPESA DATE );

  -- 2°Record definito dall'utente
TYPE CLIENTI_TYPE
IS
  RECORD
  (
    CARD CARD_TYPE,
    NOMINATIVO VARCHAR2(100),
    PROVINCIA  VARCHAR2(3) );

  CLIENTI_REC CLIENTI_TYPE;

BEGIN

  SELECT
    A.CODFIDELITY,
    A.NOME
    || ' '
    || A.COGNOME,
    A.PROV,
    A.BOLLINI,
    A.ULTIMASPESA
  INTO
    CLIENTI_REC.CARD.CODFIDELITY,
    CLIENTI_REC.NOMINATIVO,
    CLIENTI_REC.PROVINCIA,
    CLIENTI_REC.CARD.BOLLINI,
    CLIENTI_REC.CARD.ULTIMASPESA
  FROM
    VW_CLIENTI A
  WHERE
    a.CODFIDELITY = '67100724';

  DBMS_OUTPUT.PUT_LINE ('NOMINATIVO: '||CLIENTI_REC.NOMINATIVO);
  DBMS_OUTPUT.PUT_LINE ('CodFid: '||CLIENTI_REC.CARD.CODFIDELITY);
  DBMS_OUTPUT.PUT_LINE ('BOLLINI: '||CLIENTI_REC.CARD.BOLLINI);
  DBMS_OUTPUT.PUT_LINE ('Ultima Spesa: '||CLIENTI_REC.CARD.ULTIMASPESA);
  DBMS_OUTPUT.PUT_LINE ('Prov: '||CLIENTI_REC.PROVINCIA);

END; 