-- Esempio di Table Based Record

DECLARE
  ARTICOLO_REC ARTICOLI%ROWTYPE;
BEGIN
  SELECT
    *
  INTO
    ARTICOLO_REC
  FROM
    ARTICOLI
  WHERE
    CODART = '001122501';

  DBMS_OUTPUT.PUT_LINE ('Codice: '||ARTICOLO_REC.CODART);
  DBMS_OUTPUT.PUT_LINE ('Descrizione: '||ARTICOLO_REC.DESCRIZIONE);
  DBMS_OUTPUT.PUT_LINE ('Pezzi x Cartone: '||ARTICOLO_REC.PZCART);

END;