DECLARE
  V_BOLLINI CARDS.BOLLINI%TYPE;
  V_CODICEFID CARDS.CODFIDELITY%TYPE := &CODFID;
BEGIN

  SELECT
    BOLLINI
  INTO
    V_BOLLINI
  FROM
    CARDS
  WHERE
    CODFIDELITY = V_CODICEFID;
  
  DBMS_OUTPUT.PUT_LINE('Record Coinvolti: ' || SQL%ROWCOUNT);
  DBMS_OUTPUT.PUT_LINE('Monte Bollini: ' || V_BOLLINI);
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN -- RECORD NON TROVATO
    DBMS_OUTPUT.PUT_LINE('Codice fidelity inesistente: ' || V_CODICEFID);
  WHEN TOO_MANY_ROWS THEN -- ERRORE GRAVE, INTEGRITÀ NON RISPETTATA
    DBMS_OUTPUT.PUT_LINE('Integrità dei dati compromessa in: ' || V_CODICEFID);
    RAISE;
END;
