
CREATE OR REPLACE PACKAGE GestClienti
AS

PROCEDURE Sp_SelStorSpese (CODFID_I IN CARDS.CODFIDELITY%TYPE,
                           RECORDSET_P OUT SYS_REFCURSOR);

FUNCTION Uf_GetMonteBollini(CODFID_I IN CARDS.CODFIDELITY%TYPE)
        RETURN NUMBER;

END GestClienti;